uploads = []
generated = []

[[outputs]]
id = "8cVMa2UY6N2_sHMAgmi00"
uri = "file://tabnotes-extension.zip"
type = "unspecified"
title = "TabNotes — Extensión Chrome (ZIP)"

[[outputs]]
id = "yGh-dqiL_8Sp42gBb__Sd"
uri = "file://store/tabnotes-extension-v1.1.0.zip"
type = "unspecified"
title = "TabNotes Extension v1.1.0 — Chrome"

[[outputs]]
id = "GY68eOWoy2egnUlAFFf6L"
uri = "file://store/tabnotes-extension-v1.2.0.zip"
type = "unspecified"
title = "TabNotes Extension v1.2.0 — Bugs corregidos"

[[outputs]]
id = "71Ym47-KfQzKt47eKAvgc"
uri = "file://store/tabnotes-extension-v1.3.0.zip"
type = "unspecified"
title = "TabNotes Extension v1.3.0 — Multi-nota por contexto"
